/* Generated by AN DISI Unibo */ 
package it.unibo.ctxConsole;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhinput extends AbstractEvhinput { 
	public Evhinput(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
