/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
 */
package it.unibo.controller;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Controller extends AbstractController { 
	public int DMIN=70;
	public int num_of_sonar=3;
	public int reached_sonar=1;
	public Controller(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public String evaluateExpr(int lenghTSonar1,int lenghTSonar2,int lenghTSonar3){
		System.out.println("Sto valutando l'espressione");
		if(reached_sonar==4){
			return "alarm";
		}
		else{

			int totalLenght=lenghTSonar1+lenghTSonar2+lenghTSonar3;
			if(reached_sonar==2)
				totalLenght=totalLenght-lenghTSonar1;
			if(reached_sonar==3)
				totalLenght=totalLenght-lenghTSonar2;

			if(totalLenght/(num_of_sonar-reached_sonar+1)<DMIN){
				reached_sonar++;
				return "takePhoto";
			}
			return "";
		}
	}
}
