/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.agentprototype;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Agentprototype extends AbstractAgentprototype { 
	public Agentprototype(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
